name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.0.0
        with:
          # Repository name with owner. For example, actions/checkout
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          ssh-strict: true
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-depth: 1
          show-progress: true
          set-safe-directory: true

      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.x
          check-latest: true

      - name: Install Dependencies
        run: pip install -r requirements.txt
